const FUNCTIONALITY_DEFINITIONS = [
  {
    key: "dashboard.view",
    label: "Voir le tableau de bord",
    group: "dashboard",
  },
  {
    key: "audit.view",
    label: "Consulter le journal d'audit",
    group: "audit",
  },
  { key: "clients.view", label: "Voir les clients", group: "clients" },
  { key: "clients.create", label: "Creer les clients", group: "clients" },
  { key: "clients.update", label: "Modifier les clients", group: "clients" },
  { key: "clients.delete", label: "Supprimer les clients", group: "clients" },
  { key: "clients.export", label: "Exporter les clients", group: "clients" },
  {
    key: "clients.documents",
    label: "Gerer les documents clients",
    group: "clients",
  },
  {
    key: "clients.rgpd",
    label: "Exporter et effacer les donnees personnelles (RGPD)",
    group: "clients",
  },
  { key: "prospects.view", label: "Voir les prospects", group: "prospects" },
  { key: "prospects.create", label: "Creer les prospects", group: "prospects" },
  {
    key: "prospects.update",
    label: "Modifier les prospects",
    group: "prospects",
  },
  {
    key: "prospects.delete",
    label: "Supprimer les prospects",
    group: "prospects",
  },
  { key: "projects.view", label: "Voir les projets", group: "projects" },
  { key: "projects.create", label: "Creer les projets", group: "projects" },
  { key: "projects.update", label: "Modifier les projets", group: "projects" },
  { key: "projects.delete", label: "Supprimer les projets", group: "projects" },
  { key: "tasks.view", label: "Voir les taches", group: "tasks" },
  {
    key: "tasks.all",
    label: "Voir les taches de tous les departements",
    group: "tasks",
  },
  { key: "tasks.create", label: "Creer les taches", group: "tasks" },
  { key: "tasks.update", label: "Modifier les taches", group: "tasks" },
  { key: "tasks.delete", label: "Supprimer les taches", group: "tasks" },
  { key: "tasks.assign", label: "Affecter les taches", group: "tasks" },
  {
    key: "tasks.status",
    label: "Changer le statut des taches",
    group: "tasks",
  },
  {
    key: "invoices.view",
    label: "Voir les devis et factures",
    group: "invoices",
  },
  {
    key: "invoices.create",
    label: "Creer les devis et factures",
    group: "invoices",
  },
  {
    key: "invoices.update",
    label: "Modifier les devis et factures",
    group: "invoices",
  },
  {
    key: "invoices.delete",
    label: "Supprimer les devis et factures",
    group: "invoices",
  },
  { key: "invoices.send", label: "Envoyer les devis", group: "invoices" },
  { key: "invoices.credit", label: "Preparer les avoirs", group: "invoices" },
  {
    key: "invoices.credit.issue",
    label: "Emettre et imputer les avoirs",
    group: "invoices",
  },
  { key: "invoices.pdf", label: "Generer les PDF", group: "invoices" },
  { key: "finances.view", label: "Voir les finances", group: "finances" },
  {
    key: "finances.reconcile",
    label: "Rapprochement bancaire",
    group: "finances",
  },
  { key: "finances.import", label: "Importer les releves", group: "finances" },
  {
    key: "finances.currencies",
    label: "Tenir les taux de change",
    group: "finances",
  },
  {
    key: "finances.decaissements",
    label: "Gerer les decaissements",
    group: "finances",
  },
  { key: "hr.view", label: "Voir RH", group: "hr" },
  {
    key: "hr.employees",
    label: "Voir l'annuaire des employes",
    group: "hr",
  },
  { key: "hr.create", label: "Creer les employes", group: "hr" },
  { key: "hr.update", label: "Modifier les employes", group: "hr" },
  { key: "hr.delete", label: "Supprimer les employes", group: "hr" },
  { key: "hr.leaves", label: "Gerer les conges", group: "hr" },
  { key: "hr.attendance", label: "Gerer la presence", group: "hr" },
  { key: "hr.care", label: "Gerer les soins", group: "hr" },
  { key: "hr.loans", label: "Gerer les prets du personnel", group: "hr" },
  { key: "users.view", label: "Voir les utilisateurs", group: "users" },
  { key: "users.create", label: "Creer les utilisateurs", group: "users" },
  { key: "users.update", label: "Modifier les utilisateurs", group: "users" },
  { key: "users.delete", label: "Supprimer les utilisateurs", group: "users" },
  { key: "users.permissions", label: "Gerer les permissions", group: "users" },
  { key: "marketing.view", label: "Voir le marketing", group: "marketing" },
  {
    key: "marketing.create",
    label: "Creer les campagnes",
    group: "marketing",
  },
  {
    key: "marketing.update",
    label: "Modifier les campagnes",
    group: "marketing",
  },
  {
    key: "marketing.delete",
    label: "Supprimer les campagnes",
    group: "marketing",
  },
  { key: "marketing.send", label: "Envoyer les campagnes", group: "marketing" },
  { key: "payroll.view", label: "Voir la paie", group: "payroll" },
  { key: "payroll.create", label: "Generer la paie", group: "payroll" },
  { key: "payroll.update", label: "Modifier la paie", group: "payroll" },
  { key: "payroll.approve", label: "Approuver la paie", group: "payroll" },
  { key: "payroll.pay", label: "Marquer paie payee", group: "payroll" },
  { key: "payroll.export", label: "Exporter la paie", group: "payroll" },
  { key: "payroll.rules", label: "Gerer les regles de paie", group: "payroll" },
  {
    key: "catalog.view",
    label: "Voir le catalogue de services",
    group: "catalog",
  },
  {
    key: "catalog.manage",
    label: "Gerer le catalogue de services",
    group: "catalog",
  },
  {
    key: "subscriptions.view",
    label: "Voir les abonnements",
    group: "subscriptions",
  },
  {
    key: "subscriptions.manage",
    label: "Gerer les abonnements",
    group: "subscriptions",
  },
  {
    key: "purchases.view",
    label: "Voir le module achats",
    group: "purchases",
  },
  {
    key: "purchases.requests.create",
    label: "Creer les demandes d'achat",
    group: "purchases",
  },
  {
    key: "purchases.requests.approve",
    label: "Approuver les demandes d'achat",
    group: "purchases",
  },
  {
    key: "purchases.rfq.manage",
    label: "Gerer les demandes de prix",
    group: "purchases",
  },
  {
    key: "purchases.rfq.award",
    label: "Attribuer une offre fournisseur",
    group: "purchases",
  },
  {
    key: "purchases.orders.create",
    label: "Emettre les commandes d'achat",
    group: "purchases",
  },
  {
    key: "purchases.orders.validate",
    label: "Valider les commandes d'achat",
    group: "purchases",
  },
  {
    key: "purchases.orders.receive",
    label: "Receptionner les commandes d'achat",
    group: "purchases",
  },

  {
    key: "departments.view",
    label: "Voir les departements",
    group: "departments",
  },
  {
    key: "departments.manage",
    label: "Gerer les departements et leurs responsables",
    group: "departments",
  },

  {
    key: "budget.view",
    label: "Consulter les budgets",
    group: "budget",
  },
  {
    key: "budget.create",
    label: "Preparer les budgets",
    group: "budget",
  },
  {
    key: "budget.update",
    label: "Modifier les budgets",
    group: "budget",
  },
  {
    key: "budget.validate",
    label: "Voter et cloturer les budgets",
    group: "budget",
  },
  {
    key: "budget.delete",
    label: "Supprimer les budgets",
    group: "budget",
  },
  {
    key: "budget.analysis",
    label: "Analyser les ecarts budgetaires",
    group: "budget",
  },

  {
    key: "commercial.view",
    label: "Voir les objectifs commerciaux",
    group: "commercial",
  },
  {
    key: "commercial.manage",
    label: "Definir les objectifs commerciaux",
    group: "commercial",
  },
];

const MODULE_PERMISSIONS = FUNCTIONALITY_DEFINITIONS.map(
  (definition) => definition.key,
);

const ROLE_DEFAULT_PERMISSIONS = {
  super_admin: [...MODULE_PERMISSIONS],
  administrateur: [
    "commercial.view",
    "commercial.manage",
    "budget.view",
    "budget.create",
    "budget.update",
    "budget.validate",
    "budget.delete",
    "budget.analysis",
    "departments.view",
    "departments.manage",
    "purchases.view",
    "purchases.requests.create",
    "purchases.requests.approve",
    "purchases.rfq.manage",
    "purchases.rfq.award",
    "purchases.orders.create",
    "purchases.orders.validate",
    "purchases.orders.receive",
    "finances.currencies",
    "catalog.view",
    "catalog.manage",
    "invoices.credit",
    "invoices.credit.issue",
    "subscriptions.view",
    "subscriptions.manage",
    "clients.documents",
    "clients.rgpd",
    "audit.view",
    "hr.care",
    "hr.loans",
    "tasks.all",
    "users.view",
    "users.create",
    "users.update",
    "users.delete",
    "users.permissions",
    "marketing.view",
    "marketing.create",
    "marketing.update",
    "marketing.delete",
    "marketing.send",
    "dashboard.view",
    "clients.view",
    "clients.create",
    "clients.update",
    "clients.delete",
    "clients.export",
    "prospects.view",
    "prospects.create",
    "prospects.update",
    "prospects.delete",
    "projects.view",
    "projects.create",
    "projects.update",
    "projects.delete",
    "tasks.view",
    "tasks.create",
    "tasks.update",
    "tasks.delete",
    "tasks.assign",
    "tasks.status",
    "invoices.view",
    "invoices.create",
    "invoices.update",
    "invoices.delete",
    "invoices.send",
    "invoices.pdf",
    "finances.view",
    "finances.reconcile",
    "finances.import",
    "finances.decaissements",
    "hr.view",
    "hr.employees",
    "hr.create",
    "hr.update",
    "hr.delete",
    "hr.leaves",
    "hr.attendance",
    "payroll.view",
    "payroll.create",
    "payroll.update",
    "payroll.approve",
    "payroll.pay",
    "payroll.export",
    "payroll.rules",
  ],
  manager: [
    "commercial.view",
    "commercial.manage",
    "budget.view",
    "departments.view",
    "purchases.view",
    "purchases.requests.create",
    "purchases.requests.approve",
    "purchases.orders.validate",
    "catalog.view",
    "catalog.manage",
    "subscriptions.view",
    "clients.documents",
    "tasks.all",
    "users.view",
    "marketing.view",
    "marketing.create",
    "marketing.update",
    "marketing.send",
    "dashboard.view",
    "clients.view",
    "clients.create",
    "clients.update",
    "clients.export",
    "prospects.view",
    "prospects.create",
    "prospects.update",
    "projects.view",
    "projects.create",
    "projects.update",
    "projects.delete",
    "tasks.view",
    "tasks.create",
    "tasks.update",
    "tasks.assign",
    "tasks.status",
    "invoices.view",
    "invoices.create",
    "invoices.update",
    "invoices.send",
    "invoices.pdf",
    "finances.view",
    "finances.reconcile",
    "hr.view",
    "hr.employees",
    "hr.create",
    "hr.update",
    "hr.delete",
    "hr.leaves",
    "hr.attendance",
    "payroll.view",
    "payroll.create",
    "payroll.update",
  ],
  commercial: [
    "commercial.view",
    "purchases.view",
    "purchases.requests.create",
    "catalog.view",
    "subscriptions.view",
    "clients.documents",
    "marketing.view",
    "marketing.create",
    "marketing.update",
    "marketing.send",
    "dashboard.view",
    "clients.view",
    "clients.create",
    "clients.update",
    "clients.export",
    "prospects.view",
    "prospects.create",
    "prospects.update",
    "tasks.view",
    "tasks.create",
    "tasks.update",
    "invoices.view",
    "invoices.create",
    "invoices.update",
    "invoices.send",
    "invoices.pdf",
    "hr.view",
    "hr.leaves",
    "hr.attendance",
  ],
  comptable: [
    "commercial.view",
    "budget.view",
    "purchases.requests.create",
    "purchases.view",
    "finances.currencies",
    "catalog.view",
    "invoices.credit",
    "invoices.credit.issue",
    "subscriptions.view",
    "subscriptions.manage",
    "clients.documents",
    "hr.loans",
    "dashboard.view",
    "clients.view",
    "clients.export",
    "invoices.view",
    "invoices.create",
    "invoices.update",
    "invoices.delete",
    "invoices.send",
    "invoices.pdf",
    "finances.view",
    "finances.reconcile",
    "finances.import",
    "finances.decaissements",
    "payroll.view",
    "payroll.pay",
    "payroll.export",
    "hr.view",
    "hr.leaves",
    "hr.attendance",
  ],
  // Responsable des ressources humaines : dossiers du personnel, conges,
  // presence, et cycle de paie jusqu'a l'approbation. Le reglement effectif
  // reste au Comptable (payroll.pay), afin que celui qui prepare la paie ne
  // soit pas celui qui la decaisse.
  rh: [
    "departments.view",
    "departments.manage",
    "purchases.view",
    "purchases.requests.create",
    "hr.care",
    "hr.loans",
    "dashboard.view",
    "tasks.view",
    "tasks.status",
    "hr.view",
    "hr.employees",
    "hr.create",
    "hr.update",
    "hr.delete",
    "hr.leaves",
    "hr.attendance",
    "payroll.view",
    "payroll.create",
    "payroll.update",
    "payroll.approve",
    "payroll.export",
    "payroll.rules",
  ],
  // Gestionnaire achat : conduit le flux du besoin a la reception. Il ne
  // valide pas la commande — engager l'entreprise appelle un second regard,
  // de la meme facon que la paie separe la preparation du reglement.
  // Direction generale : dernier niveau du circuit d'approbation des achats,
  // et vision d'ensemble. Elle ne saisit pas, elle arbitre.
  directeur_general: [
    "commercial.view",
    "commercial.manage",
    "budget.view",
    "budget.validate",
    "budget.analysis",
    "dashboard.view",
    "audit.view",
    "departments.view",
    "departments.manage",
    "tasks.view",
    "tasks.all",
    "hr.view",
    "hr.employees",
    "hr.leaves",
    "hr.attendance",
    "clients.view",
    "prospects.view",
    "projects.view",
    "invoices.view",
    "finances.view",
    "catalog.view",
    "subscriptions.view",
    "marketing.view",
    "payroll.view",
    "purchases.view",
    "purchases.requests.create",
    "purchases.requests.approve",
    "purchases.orders.receive",
    "purchases.orders.validate",
  ],
  // Directeur de departement. Le departement dont il repond n'est pas porte
  // par le role mais par la fiche du departement, qui le designe comme
  // responsable : creer un service n'oblige ainsi a modifier aucun code.
  // --- Directions fonctionnelles ---
  // Chaque direction porte son titre reel : « DAF », « DRH », « DSI » disent
  // ce que « directeur de departement » taisait. Le perimetre, lui, reste
  // porte par la fiche du departement, qui declare le role qui le dirige :
  // creer un service ne demande donc toujours aucune modification de code.

  // DAF — finances, facturation, tresorerie. Approuve les demandes de la
  // comptabilite.
  directeur_administratif_financier: [
    "commercial.view",
    "budget.view",
    "budget.create",
    "budget.update",
    "budget.analysis",
    "dashboard.view",
    "departments.view",
    "audit.view",
    "tasks.view",
    "tasks.all",
    "hr.view",
    "hr.leaves",
    "hr.attendance",
    "clients.view",
    "invoices.view",
    "invoices.create",
    "invoices.update",
    "invoices.credit",
    "invoices.credit.issue",
    "finances.view",
    "finances.reconcile",
    "finances.import",
    "finances.decaissements",
    "finances.currencies",
    "subscriptions.view",
    "catalog.view",
    "payroll.view",
    "payroll.pay",
    "payroll.export",
    "purchases.view",
    "purchases.requests.create",
    "purchases.requests.approve",
    "purchases.orders.receive",
    "purchases.orders.validate",
  ],
  // DRH — effectifs, conges, paie jusqu'a l'approbation.
  directeur_ressources_humaines: [
    "budget.view",
    "dashboard.view",
    "departments.view",
    "departments.manage",
    "tasks.view",
    "tasks.all",
    "hr.view",
    "hr.employees",
    "hr.create",
    "hr.update",
    "hr.delete",
    "hr.leaves",
    "hr.attendance",
    "hr.care",
    "hr.loans",
    "payroll.view",
    "payroll.create",
    "payroll.update",
    "payroll.approve",
    "payroll.export",
    "payroll.rules",
    "purchases.view",
    "purchases.requests.create",
    "purchases.requests.approve",
    "purchases.orders.validate",
    "purchases.orders.receive",
  ],
  // Directeur commercial — clients, prospects, devis.
  directeur_commercial: [
    "commercial.view",
    "commercial.manage",
    "dashboard.view",
    "departments.view",
    "tasks.view",
    "tasks.all",
    "tasks.assign",
    "hr.view",
    "hr.leaves",
    "hr.attendance",
    "clients.view",
    "clients.create",
    "clients.update",
    "clients.export",
    "prospects.view",
    "prospects.create",
    "prospects.update",
    "prospects.delete",
    "invoices.view",
    "invoices.create",
    "invoices.update",
    "invoices.send",
    "invoices.pdf",
    "catalog.view",
    "subscriptions.view",
    "purchases.view",
    "purchases.requests.create",
    "purchases.requests.approve",
    "purchases.orders.validate",
    "purchases.orders.receive",
  ],
  // DSI — systemes d'information, projets techniques.
  directeur_systemes_information: [
    "budget.view",
    "dashboard.view",
    "departments.view",
    "audit.view",
    "tasks.view",
    "tasks.all",
    "tasks.create",
    "tasks.update",
    "tasks.assign",
    "tasks.status",
    "hr.view",
    "hr.leaves",
    "hr.attendance",
    "projects.view",
    "projects.create",
    "projects.update",
    "projects.delete",
    "catalog.view",
    "purchases.view",
    "purchases.requests.create",
    "purchases.requests.approve",
    "purchases.orders.validate",
    "purchases.orders.receive",
  ],
  // Directeur de production — realisation des projets clients.
  directeur_production: [
    "budget.view",
    "dashboard.view",
    "departments.view",
    "tasks.view",
    "tasks.all",
    "tasks.create",
    "tasks.update",
    "tasks.assign",
    "tasks.status",
    "hr.view",
    "hr.leaves",
    "hr.attendance",
    "clients.view",
    "projects.view",
    "projects.create",
    "projects.update",
    "projects.delete",
    "catalog.view",
    "purchases.view",
    "purchases.requests.create",
    "purchases.requests.approve",
    "purchases.orders.validate",
    "purchases.orders.receive",
  ],
  // Directeur marketing — campagnes et acquisition.
  directeur_marketing: [
    "budget.view",
    "dashboard.view",
    "departments.view",
    "tasks.view",
    "tasks.all",
    "tasks.assign",
    "hr.view",
    "hr.leaves",
    "hr.attendance",
    "clients.view",
    "prospects.view",
    "marketing.view",
    "marketing.create",
    "marketing.update",
    "marketing.delete",
    "marketing.send",
    "purchases.view",
    "purchases.requests.create",
    "purchases.requests.approve",
    "purchases.orders.validate",
    "purchases.orders.receive",
  ],
  // --- Controle de gestion ---
  // Le directeur du controle de gestion vote les budgets et arbitre les
  // ecarts ; ses collaborateurs les preparent et les analysent sans pouvoir
  // les voter. Preparer et approuver restent deux actes distincts, ici comme
  // ailleurs dans l'outil.
  directeur_controle_gestion: [
    "commercial.view",
    "commercial.manage",
    "dashboard.view",
    "departments.view",
    "audit.view",
    "tasks.view",
    "tasks.all",
    "hr.view",
    "hr.leaves",
    "hr.attendance",
    "clients.view",
    "projects.view",
    "invoices.view",
    "finances.view",
    "catalog.view",
    "subscriptions.view",
    "payroll.view",
    "budget.view",
    "budget.create",
    "budget.update",
    "budget.validate",
    "budget.delete",
    "budget.analysis",
    "purchases.view",
    "purchases.requests.create",
    "purchases.requests.approve",
    "purchases.orders.validate",
    "purchases.orders.receive",
  ],
  // Controleur de gestion : il instruit, il n'arbitre pas.
  controleur_gestion: [
    "commercial.view",
    "dashboard.view",
    "departments.view",
    "tasks.view",
    "hr.view",
    "hr.leaves",
    "hr.attendance",
    "clients.view",
    "projects.view",
    "invoices.view",
    "finances.view",
    "catalog.view",
    "payroll.view",
    "budget.view",
    "budget.create",
    "budget.update",
    "budget.analysis",
    "purchases.view",
    "purchases.requests.create",
  ],
  gestionnaire_achat: [
    "dashboard.view",
    "tasks.view",
    "tasks.status",
    "hr.view",
    "hr.leaves",
    "hr.attendance",
    "catalog.view",
    "finances.view",
    "purchases.view",
    "purchases.requests.create",
    "purchases.requests.approve",
    "purchases.orders.validate",
    "purchases.rfq.manage",
    "purchases.rfq.award",
    "purchases.orders.create",
    "purchases.orders.receive",
  ],
  employe: [
    "purchases.view",
    "purchases.requests.create",
    "dashboard.view",
    "tasks.view",
    "tasks.update",
    "tasks.status",
    "hr.view",
    "hr.leaves",
    "hr.attendance",
  ],
};

const DEFAULT_PERMISSION_MODE = "role";

const normalizeRole = (role) =>
  String(role || "")
    .trim()
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");

const normalizePermission = (permission) =>
  String(permission || "")
    .trim()
    .toLowerCase();

const sanitizePermissions = (permissions = []) => {
  if (!Array.isArray(permissions)) {
    return [];
  }

  return [
    ...new Set(
      permissions
        .map(normalizePermission)
        .filter((permission) => MODULE_PERMISSIONS.includes(permission)),
    ),
  ];
};

const getDefaultPermissionsForRole = (role) =>
  ROLE_DEFAULT_PERMISSIONS[normalizeRole(role)] || [];

const matchesPermissionGroup = (permission, group) =>
  permission === group || permission.startsWith(`${group}.`);

const getEffectivePermissions = (user) => {
  if (!user) {
    return [];
  }

  const permissionMode = String(user.permissionMode || DEFAULT_PERMISSION_MODE)
    .trim()
    .toLowerCase();
  const explicitPermissions = sanitizePermissions(user.permissions || []);
  if (permissionMode === "custom") {
    return explicitPermissions;
  }

  return getDefaultPermissionsForRole(user.role);
};

const canAccessModule = (user, moduleName) => {
  if (!user) {
    return false;
  }

  if (normalizeRole(user.role) === "super_admin") {
    return true;
  }

  const normalizedModule = normalizePermission(moduleName);
  return getEffectivePermissions(user).some((permission) =>
    matchesPermissionGroup(normalizePermission(permission), normalizedModule),
  );
};

module.exports = {
  MODULE_PERMISSIONS,
  FUNCTIONALITY_DEFINITIONS,
  ROLE_DEFAULT_PERMISSIONS,
  DEFAULT_PERMISSION_MODE,
  canAccessModule,
  getDefaultPermissionsForRole,
  getEffectivePermissions,
  normalizePermission,
  normalizeRole,
  sanitizePermissions,
};
